spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enjoymall?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root

logging:
  level:
    cn.tedu.jsd2307enjoymall: trace